import gleam/int
import gleam/list
import gleam/string
import glsql/internal/resolve.{type ResolvedColumn, type ResolvedTable}

pub fn generate_table(
  table: ResolvedTable,
  driver: String,
  source: String,
) -> String {
  string.join(
    [
      header(table, source),
      imports(table, driver),
      record(table),
      constants(table),
      decoder(table),
      encoder(table, driver),
      metadata(table),
    ],
    "\n",
  )
}

fn header(table: ResolvedTable, source: String) -> String {
  "// "
  <> table.module_name
  <> ".gleam\n// Generated by glsql from "
  <> source
  <> ". Do not edit.\n"
}

fn imports(table: ResolvedTable, driver: String) -> String {
  let needs_option = list.any(table.columns, fn(c) { c.nullable })

  let base = ["gleam/dynamic/decode", "glsql/schema", driver]
  let base = case needs_option {
    True -> ["gleam/option", ..base]
    False -> base
  }

  let custom = list.flat_map(table.columns, fn(c) { c.imports })

  let all =
    list.append(base, custom)
    |> list.unique
    |> list.sort(string.compare)

  all
  |> list.map(fn(m) {
    case m {
      "gleam/option" -> "import gleam/option.{type Option}"
      "glsql/schema" -> "import glsql/schema.{type Column, Column}"
      _ -> "import " <> m
    }
  })
  |> string.join("\n")
  |> string.append("\n")
}

fn record(table: ResolvedTable) -> String {
  let fields =
    table.columns
    |> list.map(fn(c) { "    " <> c.field_name <> ": " <> c.gleam_type <> "," })
    |> string.join("\n")

  "pub type "
  <> table.type_name
  <> " {\n  "
  <> table.type_name
  <> "(\n"
  <> fields
  <> "\n  )\n}\n"
}

fn constants(table: ResolvedTable) -> String {
  let names =
    table.columns
    |> list.map(fn(c) { c.sql_name })
    |> string.join(", ")

  "pub const table: String = \""
  <> table.sql_name
  <> "\"\n\n/// Columns in declaration order. Pair with `decoder()` so the SELECT\n/// order always matches the positional decoder.\npub const columns: String = \""
  <> names
  <> "\"\n"
}

fn decoder(table: ResolvedTable) -> String {
  let fields =
    table.columns
    |> list.index_map(fn(c, i) {
      "  use "
      <> c.field_name
      <> " <- decode.field("
      <> int.to_string(i)
      <> ", "
      <> c.decoder
      <> ")"
    })
    |> string.join("\n")

  let labels =
    table.columns
    |> list.map(fn(c) { c.field_name <> ":" })
    |> string.join(", ")

  "pub fn decoder() -> decode.Decoder("
  <> table.type_name
  <> ") {\n"
  <> fields
  <> "\n  decode.success("
  <> table.type_name
  <> "("
  <> labels
  <> "))\n}\n"
}

fn encoder(table: ResolvedTable, driver: String) -> String {
  let values =
    table.columns
    |> list.map(fn(c) { "    " <> encode_value(c) <> "," })
    |> string.join("\n")

  "pub fn to_params(row: "
  <> table.type_name
  <> ") -> List("
  <> driver
  <> ".Value) {\n  [\n"
  <> values
  <> "\n  ]\n}\n"
}

fn encode_value(c: ResolvedColumn) -> String {
  let is_list = string.contains(c.gleam_type, "List(")

  let element = fn(var: String) -> String {
    string.replace(c.encoder, "$", var)
  }

  let value = fn(var: String) -> String {
    case is_list {
      True -> "pog.array(fn(v) { " <> element("v") <> " }, " <> var <> ")"
      False -> element(var)
    }
  }

  case c.nullable {
    True ->
      "pog.nullable(fn(v) { " <> value("v") <> " }, row." <> c.field_name <> ")"
    False -> value("row." <> c.field_name)
  }
}

fn metadata(table: ResolvedTable) -> String {
  table.columns
  |> list.map(fn(c) { column_const(table, c) })
  |> string.join("\n\n")
  |> string.append("\n")
}

fn column_const(table: ResolvedTable, c: ResolvedColumn) -> String {
  "pub const col_"
  <> c.field_name
  <> ": Column("
  <> c.gleam_type
  <> ") =\n  Column(\""
  <> table.sql_name
  <> "\", \""
  <> c.sql_name
  <> "\", \""
  <> c.sql_type_name
  <> "\", "
  <> bool_literal(c.nullable)
  <> ", "
  <> bool_literal(c.primary_key)
  <> ")"
}

fn bool_literal(value: Bool) -> String {
  case value {
    True -> "True"
    False -> "False"
  }
}
