import gleam/int
import gleam/list
import gleam/string
import glsql/internal/resolve.{type ResolvedColumn, type ResolvedTable}

/// File name, without `.gleam`, of the generated module holding the `Column`
/// type. Prefixed so it cannot clash with a table of the same name.
pub const schema_module = "glsql_schema"

/// What the generated modules put in front of each other's names to import
/// them. Gleam names a module by its path below `src` or `test`, so everything
/// up to and including that directory is left out. Taking the last one means an
/// out_dir written as a longer path, or as an absolute one, still gives a name
/// the project can import.
pub fn module_prefix(out_dir: String) -> String {
  let inner =
    out_dir
    |> string.split("/")
    |> list.fold([], fn(acc, part) {
      case part {
        "src" | "test" | "dev" -> []
        "" -> acc
        _ -> [part, ..acc]
      }
    })
    |> list.reverse
    |> string.join("/")

  case inner {
    "" -> ""
    _ -> inner <> "/"
  }
}

/// The `Column` type the `col_*` accessors return. Generated next to the table
/// modules rather than imported from glsql, so a project only needs glsql while
/// generating and not to build what it generated.
pub fn generate_schema_module(source: String) -> String {
  "// "
  <> schema_module
  <> ".gleam\n// Generated by glsql from "
  <> source
  <> ". Do not edit.\n\nimport gleam/dynamic/decode\n\n/// A column descriptor. The `value` type parameter records the Gleam type\n/// of the column, and `decoder` decodes just that column, so a query that\n/// selects fewer than all of a table's columns can still be decoded type\n/// safely by composing the pieces it needs.\npub type Column(value) {\n  Column(\n    table: String,\n    name: String,\n    sql_type: String,\n    nullable: Bool,\n    primary_key: Bool,\n    decoder: decode.Decoder(value),\n  )\n}\n"
}

pub fn generate_table(
  table: ResolvedTable,
  driver: String,
  source: String,
  schema_import: String,
) -> String {
  string.join(
    [
      header(table, source),
      imports(table, driver, schema_import),
      record(table),
      constants(table),
      decoder(table),
      encoder(table, driver),
      metadata(table),
    ],
    "\n",
  )
}

fn header(table: ResolvedTable, source: String) -> String {
  "// "
  <> table.module_name
  <> ".gleam\n// Generated by glsql from "
  <> source
  <> ". Do not edit.\n"
}

fn imports(
  table: ResolvedTable,
  driver: String,
  schema_import: String,
) -> String {
  let needs_option = list.any(table.columns, fn(c) { c.nullable })

  let base = ["gleam/dynamic/decode", schema_import, driver]
  let base = case needs_option {
    True -> ["gleam/option", ..base]
    False -> base
  }

  let custom = list.flat_map(table.columns, fn(c) { c.imports })

  let all =
    list.append(base, custom)
    |> list.unique
    |> list.sort(string.compare)

  all
  |> list.map(fn(m) {
    case m {
      "gleam/option" -> "import gleam/option.{type Option}"
      _ if m == schema_import -> "import " <> m <> ".{type Column, Column}"
      _ -> "import " <> m
    }
  })
  |> string.join("\n")
  |> string.append("\n")
}

/// The width `gleam format` wraps at.
const max_width = 80

/// Write a call the way `gleam format` would: on one line when it fits inside
/// `max_width`, otherwise one argument per line with a trailing comma. Keeping
/// to this means the generated files come out already formatted, so a project
/// running `gleam format --check` over them stays green.
fn call(
  indent: String,
  open: String,
  args: List(String),
  close: String,
) -> String {
  let one_line = indent <> open <> string.join(args, ", ") <> close
  case string.length(one_line) <= max_width {
    True -> one_line
    False -> {
      let lines =
        args
        |> list.map(fn(a) { indent <> "  " <> a <> "," })
        |> string.join("\n")
      indent <> open <> "\n" <> lines <> "\n" <> indent <> close
    }
  }
}

fn record(table: ResolvedTable) -> String {
  let fields =
    list.map(table.columns, fn(c) { c.field_name <> ": " <> c.gleam_type })
  let one_line =
    "  " <> table.type_name <> "(" <> string.join(fields, ", ") <> ")"

  let body = case string.length(one_line) <= max_width {
    True -> one_line
    False -> {
      let lines =
        table.columns
        |> list.map(record_field)
        |> string.join("\n")
      "  " <> table.type_name <> "(\n" <> lines <> "\n  )"
    }
  }

  "pub type " <> table.type_name <> " {\n" <> body <> "\n}\n"
}

/// One field of the record, indented and with its trailing comma. A field too
/// long for the line has the argument of its type broken out, which is what
/// `gleam format` does with a long `Option(...)` or `List(...)`.
fn record_field(c: ResolvedColumn) -> String {
  // The trailing comma sits outside what is measured, as with the closing
  // delimiters elsewhere.
  let one_line = "    " <> c.field_name <> ": " <> c.gleam_type
  case string.length(one_line) <= max_width {
    True -> one_line <> ","
    False ->
      case string.split_once(c.gleam_type, "(") {
        Ok(#(wrapper, rest)) ->
          "    "
          <> c.field_name
          <> ": "
          <> wrapper
          <> "(\n      "
          <> without_last_paren(rest)
          <> ",\n    ),"
        Error(Nil) -> one_line
      }
  }
}

fn without_last_paren(text: String) -> String {
  case string.ends_with(text, ")") {
    True -> string.slice(text, 0, string.length(text) - 1)
    False -> text
  }
}

fn constants(table: ResolvedTable) -> String {
  let names =
    table.columns
    |> list.map(fn(c) { c.sql_name })
    |> string.join(", ")

  "pub const table: String = \""
  <> table.sql_name
  <> "\"\n\n/// Columns in declaration order. Pair with `decoder()` so the SELECT\n/// order always matches the positional decoder.\npub const columns: String = \""
  <> names
  <> "\"\n"
}

fn decoder(table: ResolvedTable) -> String {
  let fields =
    table.columns
    |> list.index_map(fn(c, i) {
      call(
        "  ",
        "use " <> c.field_name <> " <- decode.field(",
        [int.to_string(i), c.decoder],
        ")",
      )
    })
    |> string.join("\n")

  let labels = list.map(table.columns, fn(c) { c.field_name <> ":" })

  call("", "pub fn decoder() -> decode.Decoder(", [table.type_name], ")")
  <> " {\n"
  <> fields
  <> "\n"
  // As with a function head, the outermost closing paren falls outside what
  // is measured, so it goes on after.
  <> call("  ", "decode.success(" <> table.type_name <> "(", labels, ")")
  <> ")\n}\n"
}

fn encoder(table: ResolvedTable, driver: String) -> String {
  let values =
    table.columns
    |> list.map(encode_value)
    |> string.join("\n")

  // Unlike a head with no arguments, this one is measured with its ` {`,
  // since the argument list is what gets broken up.
  call(
    "",
    "pub fn to_params(",
    ["row: " <> table.type_name],
    ") -> List(" <> driver <> ".Value) {",
  )
  <> "\n  [\n"
  <> values
  <> "\n  ]\n}\n"
}

/// The entry for one column in `to_params`, indented and with its trailing
/// comma. Anything nested inside a lambda stays on one line, since that is
/// short enough to fit whatever wraps around it.
fn encode_value(c: ResolvedColumn) -> String {
  let is_list = string.contains(c.gleam_type, "List(")
  let substitute = fn(var: String) -> String {
    string.replace(c.encoder, "$", var)
  }

  let inline_value = fn(var: String) -> String {
    case is_list {
      True -> "pog.array(fn(v) { " <> substitute("v") <> " }, " <> var <> ")"
      False -> substitute(var)
    }
  }

  let row = "row." <> c.field_name

  let body = case c.nullable, is_list {
    True, _ ->
      call(
        "    ",
        "pog.nullable(",
        ["fn(v) { " <> inline_value("v") <> " }", row],
        ")",
      )
    False, True ->
      call(
        "    ",
        "pog.array(",
        ["fn(v) { " <> substitute("v") <> " }", row],
        ")",
      )
    False, False -> {
      let #(open, close) = split_encoder(c.encoder)
      call("    ", open, [row], close)
    }
  }

  body <> ","
}

/// An encoder from a type mapping carries a `$` where the value goes, so the
/// text either side of it is what surrounds the argument.
fn split_encoder(encoder: String) -> #(String, String) {
  case string.split(encoder, "$") {
    [before, after] -> #(before, after)
    _ -> #(encoder, "")
  }
}

fn metadata(table: ResolvedTable) -> String {
  table.columns
  |> list.map(fn(c) { column_accessor(table, c) })
  |> string.join("\n\n")
  |> string.append("\n")
}

fn column_accessor(table: ResolvedTable, c: ResolvedColumn) -> String {
  // The ` {` that opens the body is appended after measuring, because a
  // function head is laid out without it.
  let signature =
    call(
      "",
      "pub fn col_" <> c.field_name <> "() -> Column(",
      [c.gleam_type],
      ")",
    )
    <> " {"

  let body =
    call(
      "  ",
      "Column(",
      [
        quoted(table.sql_name),
        quoted(c.sql_name),
        quoted(c.sql_type_name),
        bool_literal(c.nullable),
        bool_literal(c.primary_key),
        c.decoder,
      ],
      ")",
    )

  signature <> "\n" <> body <> "\n}"
}

fn quoted(value: String) -> String {
  "\"" <> value <> "\""
}

fn bool_literal(value: Bool) -> String {
  case value {
    True -> "True"
    False -> "False"
  }
}
